### ISSUE TITLE
Documentation for CalDav Scheduling Requests

### ISSUE THREAD

**Issue by jsc144** [sabre-io/dav#1055]
Ive been looking over the CalDav application as I attempt to build scheduling functionality into the nextcloud calendar app (a CalDav client). However when I come to the[ section on scheduling](http://sabre.io/dav/scheduling/), I am left with a blurb saying that 4 new methods are added when the scheduling plugin is added. What are these methods and where can I find them?

**Comment by evert** [comment]
Hi @jsc144 ,

The documentation is not really good for client developers. Even for server-developers, the documentation assumes that you already understand the scheduling standard.

The specification can be found [rfc6638](https://tools.ietf.org/html/rfc6638). As a client developer, this is your documentation.

I'm happy to give some pointers if you are stuck. If you can tell me what you're trying to do, I can give some pointers. I am closing this ticket though, because it's not really a sabre/dav issue but feel free to comment here.
