### ISSUE TITLE
Trying to set up a server with Laravel

### ISSUE THREAD

**Issue by tomnyc** [sabre-io/dav#1062]
My goal ist to have one route to the WebDav server that allows for routes like
webdavserver.com/customer1
webdavserver.com/customer2
...

I kind of got it working but no WebDav client is able to show the files,

Here is what I got so far:

I have a route with a variable customer name:
`Route::get('/{customer}', 'WebDavController@server');`

In my controller the method server looks as follows:

```
public function server($customer) {
    //maybe using $customer later

    
    $rootDirectory = new DAV\FS\Directory('webdav');
    $server = new DAV\Server($rootDirectory);

    $server->setBaseUri('/');

    $server->addPlugin(new DAV\Browser\Plugin());
    $server->exec();
}
```

In my public folder (the entry folder for all requests) the structure looks like this:
/webdav/customer1/file1.zip
/webdav/customer1/file2.key
/webdav/customer2/...

The DAV\Browser\Plugin is showing me a directory of the folder. So I assume the WebDav server is running.
But the Browser Plugin does not load any css or links correctly which points to a problem.
Furthermore no webdav client is able to read the files.

Can anyone point me in the right direction?

I have no problem getting the Webdav server running and able to be read by client applications if I follow this structure in my public folder:
/webdav/customer1/server.php
/webdav/customer1/public/file1.zip
/webdav/customer2/server.php
/webdav/customer2/public/file2.key

While this can easily be automated it feels wrong with a (WebDav)server.php for each customer folder.

**Comment by evert** [comment]
sabre/dav has it's own router, and it does a fair bit of magic that would _very likely_ interfere with Laravel. I would strongly suggest not trying this.

If you want to extend sabredav with (for example) customer specific folders, you should do this within sabredav itself.

If you need to use Laravel's ORM, or other tools, you can just bring them in. I'd imagine that Laravel is written well enough that you can use parts of it's system, but ignore other parts. You really _don't_ want laravel to handle HTTP requests and responses, so avoid controllers and routers or otherwise you're gonna have a bad time.

I imagine it's possible to get that setup to work, but I think it would probably require some fairly deep laravel and sabre/dav knowledge and a good idea of how they might interact if they work together. If you're not comfortable with a PHP debugger such as XDebug and you're not able to solve this yourself, then I'd simply suggest to avoid the problem.

**Comment by tomnyc** [comment]
> sabre/dav has it's own router, and it does a fair bit of magic that would very likely interfere with Laravel. 

Ok. That probably explains my problems.
So I guess I will go with the alternative way I mentioned in my post.
Thank you very much

**Comment by evert** [comment]
Hi, you can  actually create a single server.php and have customer-specific folders. However, you need to dive into the source a bit.

Here's a more advanced tutorial on this topic:

http://sabre.io/dav/per-user-directories/

You might be able to solve most of your issue via the first few chapters (before it gets into the 'advanced' section).
