### ISSUE TITLE
CardDAV Directory

### ISSUE THREAD

**Issue by jakejcheng** [sabre-io/dav#1084]
Can anyone shed some light on how to implement CardDAV Directory?
I'm not sure how to implement this "The interface Sabre\CardDAV\IDirectory flags the CardDAV plugin to mark an addressbook as a directory." Like where and how do I "add" this and what I should implement. All I know is that it's an ICollection.

**Comment by DeepDiver1975** [comment]
I have no idea what this is about. No idea if any client is supporting this.

Maybe @evert has an idea? THX

**Comment by evert** [comment]
Did you read this page? 

http://sabre.io/dav/carddav-directory/

**Comment by jakejcheng** [comment]
Yea but like I said, I'm not sure how to implement this "The interface Sabre\CardDAV\IDirectory flags the CardDAV plugin to mark an addressbook as a directory."

**Comment by evert** [comment]
What part of that are you having trouble with? Are you insure in general how to use PHP interfaces, or do you have trouble specifically with this one. If it's the latter, can you try and share whst you tried. 

It's very hard to help you as it's pretty vague so far.

**Comment by mikaelcom** [comment]
As @jakejcheng, I'm lost while using the CardDAV Directory Tree, in order to make my CardDav Server compatible with iOS devices, from my understanding. The Evolution client seems to work with the provided samples/addressbookserver.php but the CardDAV Directory is not sampled anywhere. Evolution worked with my integration at some point but my modifications to make it work with CardDAV Directory broke it... :(

I created the CardDavDirectory class which implements, as required, the Sabre\CardDAV\IDirectory and the Sabre\DAVACL\IACL interfaces.

But I'm sincerely lost as I'm fighting to understand what must be returned for each method that must be implemented.

I'm integrating the CarDav into my existing system, maybe the hardest way to use the project, so I use my proper backend, taking examples from the Card Dav PDO backend.
I created my proper PrincipalBackend for DAVACL too.

My Dav Server is using the Sabre\DAVACL\PrincipalCollection, the Sabre\CardDAV\AddressBookRoot and my proper CardDavDirectory as Tree nodes.

What is unclear for me is that sometimes the methods (getPrincipalByPath, getChild, getAddressBooksForUser, etc.) are called even if the user is not logged in so I have to return data that may not be valid but it forces the client to authenticate.

The principaluri is very unclear for me too, moreover the CardDavDirectory::getName result has effect on how the principaluri is then generated by the library so I wonder if it sould be contextualized depending on the point of access (principals/, principals/addressbooks/, addressbooks/).

Is there somewhere any exemple of more complete example using the [CardDAV Directory](https://sabre.io/dav/carddav-directory/) ?

Thank you :)

ps : the library is great so my lack of knowledge about how a Web/Card/Cal Dav Server works is certainly not a good point...

**Comment by evert** [comment]
CardDAV directory is a pretty specific extension that is not required for iOS. It is basically a read-only search-only company-wide addressbook.

iOS should *just work* with the exception that (as far as I'm aware) only supports 1 addressbook, and usually just grabs the first in the list. 

I'm closing this ticket as it's a bit old at this point, but feel free to reply here.

**Comment by mikaelcom** [comment]
Ok, I'll try the simpliest way, thanks for your feedback :)
