### ISSUE TITLE
release 4.0.1

### ISSUE THREAD

**Issue by staabm** [sabre-io/dav#1177]
@sabre-io/maintainers any issues which should be fixed before we can release 4.0.1?

**Comment by ByteHamster** [comment]
I am looking forward to having #1169 released because that allows to publish a Baikal update ;)

We might want to wait for a response in #1171, though. This sounds like a similar problem to the ones we fixed lately. I am only using sabre/dav together with Baikal for contacts/events. #1171 seems to be related to file handling. I don't have time to test in the next 2 weeks, unfortunately.

**Comment by DeepDiver1975** [comment]
Let's wait a few days and see what happens .... I'll happily take care about releasing 4.0.1 ..

**Comment by staabm** [comment]
ping @DeepDiver1975 - it seeems Baikal is blocked because they need 4.0.1 with https://github.com/sabre-io/Baikal/issues/764#issuecomment-522885141

**Comment by DeepDiver1975** [comment]
Starting ....
