### ISSUE TITLE
htaccess conflict

### ISSUE THREAD

**Issue by exekutive** [sabre-io/dav#1184]
I am using Nextcloud for sabreDAV services. I also have Wordpress installed on my website. When I add rewrite rules for sabreDAV "well-known" URLs (http://sabre.io/dav/service-discovery/) to my .htaccess file, then it breaks Wordpress URLs. How do I make them play nicely?

**Comment by evert** [comment]
Share your full file

**Comment by exekutive** [comment]
WordPress:

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

```
Nextcloud:

```
<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteRule ^\.well-known/host-meta /cloud/public.php?service=host-meta [QSA,L]
  RewriteRule ^\.well-known/host-meta\.json /cloud/public.php?service=host-meta-json [QSA,L]
  RewriteRule ^\.well-known/webfinger /cloud/public.php?service=webfinger [QSA,L]
  RewriteRule ^\.well-known/carddav /cloud/remote.php/dav/ [R=301,L]
  RewriteRule ^\.well-known/caldav /cloud/remote.php/dav/ [R=301,L]
</IfModule>
```

**Comment by evert** [comment]
It looks like you're using nextcloud. You should really ask the question there, not here.

Anyway, as far as I can tell you should just be able to put the well-known rules first, before the wordpress rules.

You should also really remove the `<IfModule mod_rewrite.c>` statements. They're a bad idea, because if mod_rewrite is not enabled you will want a real error, not silently ignore your configuration.

**Comment by exekutive** [comment]
that worked thank you
