### ISSUE TITLE
IMip not triggered on proxied calendars

### ISSUE THREAD

**Issue by ellion** [sabre-io/dav#1260]
Hej,

I'm running Baikal 0.6.1 and am having problems with mail invitations. If I create a task and invite people on my personal calendar everything works as expected. If I create a task on a calendar that is shared with me via proxy-write and invite people there, it doesn't trigger a mail.

I'm not very firm with php or this project in particular, but the least I can say is that IMipPlugin::schedule isn't called in latter case. 

I figured this is rather a dav issue (or misunderstanding on my behalf) than a Baikal specific issue. I hope I'm right in posting it here :)

Thanks in advance,
Daniel

**Comment by ellion** [comment]
Can anyone confirm if this is unintentional behavior? I'm not even sure if this really is an issue or just a misunderstanding on my behlaf of the concepts behind it.

**Comment by DeepDiver1975** [comment]
Let me try to recover my knowledge on this: 
The behavior of invitations (same goes for notifications by the way) on shared calendars is beyond the specifications of CalDAV.
To my understanding this simply is not possible to be implemented reliably to work in all scenarios.

In details:
In general all operations work on behalf of the owner of a calendar - in case of a shared calendar the person inviting to an event must not be the owner. This could lead to either missing invitation emails or duplicates. Furthermore follow up modifications of an event in a shared calendar need to retrigger emails and because modifications can done by different people this is all getting more and more complex.

I have been discussing this with @evert long time ago and we agreed on to simply not support this scenario.

Sorry for not having better news :man_shrugging:

**Comment by ellion** [comment]
Hey Thomas,

thanks for the in depth explanation. I can fully understand and will look out for other possible solutions.

All the best,
Daniel
