### ISSUE TITLE
DAVx5: Received non-XML 207 Multi-Status

### ISSUE THREAD

**Issue by das-bub** [sabre-io/dav#1270]
Hi,

I've already reported this [downstream](https://github.com/tchapi/davis/issues/8) and was told that it's probably a sabre/dav issue, so here it goes.

DAVx5 expects a Multi-Status response with the content-type of text/xml or application/xml, while sabre/dav responds with text/html, which breaks DAVx5.

According to everything I've read DAVx5 was working with sabre/dav before, so I'm really not sure what changed.

I'm using nginx 1.16 with php-fpm 7.3, davis 1.4.7 with sabre/dav 4.1.0 and DAVx5 3.0-ose2 (300000004).

As mentioned in the downsteram bug other clients, like iOS and the Thunderbird Lightning extension work as is.
I guess they just ignore the content-type.

Debug log: [davx5-info.txt](https://github.com/sabre-io/dav/files/4655458/davx5-info.txt)

**Comment by DeepDiver1975** [comment]
sabre/dav is used without issues with the davx client in many projects (owncloud, nextcloud, baikal and many more).
Therefor I suspect the issue more within the downstream project and I kindly ask downstream to analyse the situation first within the project scope.
As soon as you are facing a real issue in sabre I'll happily help out. THX a lot

**Comment by tchapi** [comment]
Hi Thomas — downstream project maintainer here 👋 

After investigation this specific issue is indeed on our side, but I think there is a wider problem that _could_ be addressed in **sabre/dav** to mitigate it, and it's basically that the `Server` classes uses the hardcoded `Sabre\HTTP\Sapi` class.

When using another framework that has its own and proven implementation of PSR-7, it's a hacky thing to get it to encapsulate the DAV server response since it directly writes to `php://output`.. and sends the headers right away.

It's basically the point of https://github.com/sabre-io/dav/issues/1037 — and it would be great to have some control over _how_ **sabre/dav** sends the response (could be great to have a `getResponse()` method to retrieve the full response object, so that we could send it ourselves, for instance) even if you do not go down the path of PSR-7.

In the meantime, I have fixed it (https://github.com/tchapi/davis/commit/a3dab81b4e25ba8ac146da6880974829e308dd65) by looking at the _prepared_ headers from **sabre/dav**. I guess it will do, but it would be much better to have the ability to do something before the headers are sent.

Happy to hear your thoughts whenever you have some time
Best !
Cyril

PS: @das-bub you can close this issue

**Comment by das-bub** [comment]
Closing, as this was worked around downstream.

**Comment by DeepDiver1975** [comment]
> Happy to hear your thoughts whenever you have some time

Evert already responded to #1037 - this is a bigger work task. As an alternative we could look into providing an integration point to allow overwriting the hardcoded Sabre\HTTP\Sapi class.

**Comment by DeepDiver1975** [comment]
Here we go - not 100% clean but should work:
Server::sapi is public https://github.com/sabre-io/dav/blob/d5a184c146219a220c248745c255435f4bff752d/lib/DAV/Server.php#L74 so you can set it to an object which "implements" the SAPI::sendResponse method https://github.com/sabre-io/http/blob/4bfb3834209de0a4c658e0dbe69bda794bf42e3a/lib/Sapi.php#L64

The request is still created in the ctor of Server from the SAPI::getRequest method - we can adopt this ....

Feel free to give this a try .... never the less we should define a proper interface for sapi and get rid of the static methods ....

**Comment by DeepDiver1975** [comment]
@tchapi we just merged https://github.com/sabre-io/dav/pull/1271 into master - feel free to have a look how far you get with this.

**Comment by tchapi** [comment]
Hi @DeepDiver1975 

Thanks ! That looks great and that will clearly help projects integrating sabre/dav. I will adapt my code asap
