### ISSUE TITLE
Video playing on DAV server without manuel login

### ISSUE THREAD

**Issue by emresaracoglu** [sabre-io/dav#1419]
Hello,

The videos on my website are stored on a DAV server. When the video is wanted to be played on the site's page, the browser window opens and the user name and password are asked to connect to the DAV server.

Is there a way to play the video without entering the username and password? Can I play directly with SaberDAV without logging in?

Thank you

**Comment by DeepDiver1975** [comment]
One idea can be seen in owncloud - besides `files/$user` an other folder is defined `public-files/$token`

Within the `public-files` collection a different set of plugin is loaded which is handling access.

Long story short - nothing available out of the box - especially because you only want to grant read access to the videos.


https://github.com/owncloud/core/blob/292de0f0904a85a547af4aa32a8863f222b419b6/apps/dav/lib/RootCollection.php#L74
https://github.com/owncloud/core/blob/master/apps/dav/lib/Files/PublicFiles/RootCollection.php
