### ISSUE TITLE
Composer using very old sabre vendor libs

### ISSUE THREAD

**Issue by PhilZ-cwm6** [sabre-io/dav#1498]
Is it expected that the composer is requiring old versions of sabre vendor files like xml and vobject ?
xml for example is still v2.x

Is it safe to upgrade all to dev-master for example or baikal needs the old libs ?

**Comment by DeepDiver1975** [comment]
For XML the min version is 2.0.1.
Which version is installed for you locally?

Generally speaking: don't use dev-master

**Comment by DeepDiver1975** [comment]
Just double checked - deps are setup correctly -> close

**Comment by PhilZ-cwm6** [comment]
I have locally v2. 0.1, but I see latest release is 4.0.x
It is the case for most dependencies
Can you confirm if a manual update to latest in composer is safe?

**Comment by DeepDiver1975** [comment]
It is not save. As stated above please leave the dependencies as is.

**Comment by phil-davis** [comment]
Various sabre repos have major releases that contain function parameter type and return type declarations. They also require PHP 7.4 or 8.*. I was working on doing similar for `vobject` but have not got back to it (it turned out to be a big job). When `vobject` was finished, I was planning to do similar with `sabre/dav` and make a new major version release. But it has not happened yet.

I maintain the older major version branches, and make patch releases of those when there are bug fixes available. So all fixed bugs should be fixed in the major version used by `sabre/dav` as well as the later major versions.

**Comment by phil-davis** [comment]
@DeepDiver1975 is working on dropping older PHP support in `sabre/dav`. That may (should) help get composer to pull in later dependencies.

**Comment by PhilZ-cwm6** [comment]
thank you for the feedback
I also looked at the dependencies php deprecated entries when I planned to install php 8.3 and realized it is a huge task, especially when not used to the app code sources

Thank you for all your work on Baikal
